/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package money.apresentacao;

import autenticador.Autenticavel;
import autenticador.Lancador;
import java.text.DecimalFormat;
import money.negocio.MaquinaCacaNiqueis;
import money.persistencia.MaquinaCacaNiqueisDao;

/**
 *
 * @author mouriac
 */
public class Tela extends javax.swing.JFrame
{

    private MaquinaCacaNiqueis maquina;

    /**
     * Creates new form Tela
     */
    public Tela(MaquinaCacaNiqueis maquina)
    {
        this.maquina = maquina;
        initComponents();
        atualizarTela();
    }

    public void atualizarTela()
    {
        DecimalFormat df = new DecimalFormat("###,##0.00");
        this.campoContador.setText(maquina.getContadorApostas() + "");
        this.campoLucro.setText("R$ " + df.format(maquina.getLucro()));
        this.campoPremios.setText("R$ " + df.format(maquina.getPremiosDistribuidos()));
        this.campoSaldo.setText("R$ " + df.format(maquina.getSaldoCaixa()));
        if (this.maquina.getSaldoCaixa() >= 1000 && this.maquina.getSaldoCaixa() < 10000)
        {
            this.btnApostar.setEnabled(true);
        } else
        {
            this.btnApostar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollBar1 = new javax.swing.JScrollBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnApostar = new javax.swing.JButton();
        campoContador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoResultado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnSangria = new javax.swing.JButton();
        campoSaldo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoPremios = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoLucro = new javax.swing.JTextField();
        rb1000 = new javax.swing.JRadioButton();
        rbTotal = new javax.swing.JRadioButton();
        btnAbastecer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caça-Níqueis");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));

        btnApostar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnApostar.setText("Apostar");
        btnApostar.setEnabled(false);
        btnApostar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnApostarMouseEntered(evt);
            }
        });
        btnApostar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnApostarActionPerformed(evt);
            }
        });

        campoContador.setEditable(false);
        campoContador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoContador.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setText("Contador apostas:");

        jLabel5.setText("Resultado:");

        campoResultado.setEditable(false);
        campoResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnApostar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoContador)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(campoResultado)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnApostar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(campoContador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addComponent(campoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Administração"));

        btnSangria.setText("Sangria");
        btnSangria.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSangriaActionPerformed(evt);
            }
        });

        campoSaldo.setEditable(false);
        campoSaldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setText("Saldo Caixa:");

        jLabel2.setText("Prêmios distribuídos:");

        campoPremios.setEditable(false);
        campoPremios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoPremios.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setText("Lucro:");

        campoLucro.setEditable(false);
        campoLucro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        campoLucro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        buttonGroup1.add(rb1000);
        rb1000.setSelected(true);
        rb1000.setText("R$1000,00");

        buttonGroup1.add(rbTotal);
        rbTotal.setText("Total");

        btnAbastecer.setText("Abastecer Caixa");
        btnAbastecer.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAbastecerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSangria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoSaldo)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoPremios)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoLucro)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rb1000)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbTotal)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(btnAbastecer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1000)
                    .addComponent(rbTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSangria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAbastecer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(campoSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(campoPremios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addComponent(campoLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApostarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnApostarActionPerformed
    {//GEN-HEADEREND:event_btnApostarActionPerformed
        double premio = this.maquina.apostar();
        if (premio == 0)
        {
            this.campoResultado.setText("Continue tentando");
        } else
        {
            DecimalFormat df = new DecimalFormat("###,##0.00");
            this.campoResultado.setText("Ganhou R$ " + df.format(premio));
        }
        this.atualizarTela();
    }//GEN-LAST:event_btnApostarActionPerformed

    private void btnApostarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnApostarMouseEntered
    {//GEN-HEADEREND:event_btnApostarMouseEntered
        this.campoResultado.setText("");
    }//GEN-LAST:event_btnApostarMouseEntered

    private void btnSangriaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSangriaActionPerformed
    {//GEN-HEADEREND:event_btnSangriaActionPerformed
        Autenticavel aut = new Autenticavel()
        {
            @Override
            public void inicializar()
            {
                if (rb1000.isSelected())
                {
                    maquina.sangria();
                } else
                {
                    maquina.sangriaTotal();
                }
                atualizarTela();
            }
        };

        Lancador l = new Lancador(aut);
        l.start();
    }//GEN-LAST:event_btnSangriaActionPerformed

    private void btnAbastecerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAbastecerActionPerformed
    {//GEN-HEADEREND:event_btnAbastecerActionPerformed
        this.maquina.abastecer();
        this.atualizarTela();
    }//GEN-LAST:event_btnAbastecerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        MaquinaCacaNiqueisDao dao = new MaquinaCacaNiqueisDao();
        dao.salvar(maquina);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        MaquinaCacaNiqueisDao dao = new MaquinaCacaNiqueisDao();
        dao.salvar(maquina);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbastecer;
    private javax.swing.JButton btnApostar;
    private javax.swing.JButton btnSangria;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoContador;
    private javax.swing.JTextField campoLucro;
    private javax.swing.JTextField campoPremios;
    private javax.swing.JTextField campoResultado;
    private javax.swing.JTextField campoSaldo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JRadioButton rb1000;
    private javax.swing.JRadioButton rbTotal;
    // End of variables declaration//GEN-END:variables
}
