/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maquinasorvete.apresentacao;

import autenticador.Lancador;
import maquinasorvete.negocio.MaquinaSorvete;
import maquinasorvete.negocio.ModuloAdmin;
import maquinasorvete.persistencia.MaquinaSorveteDao;
import maquinasorvete.persistencia.MaquinaSorveteDaoTxt;

/**
 *
 * @author mouriac
 */
public class Tela extends javax.swing.JFrame
{

    private MaquinaSorvete ms;
    
    /**
     * Creates new form Tela
     */
    public Tela(MaquinaSorvete ms)
    {
        this.ms = ms;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnChocolate = new javax.swing.JButton();
        btnBaunilha = new javax.swing.JButton();
        mensagem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAdm = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        btnChocolate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnChocolate.setText("CHOCOLATE");
        btnChocolate.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnChocolateMouseEntered(evt);
            }
        });
        btnChocolate.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnChocolateActionPerformed(evt);
            }
        });

        btnBaunilha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBaunilha.setText("BAUNILHA");
        btnBaunilha.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                btnBaunilhaMouseEntered(evt);
            }
        });
        btnBaunilha.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBaunilhaActionPerformed(evt);
            }
        });

        mensagem.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        mensagem.setForeground(new java.awt.Color(0, 0, 204));
        mensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ESCOLHA O SABOR");

        btnAdm.setText("Administrar");
        btnAdm.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAdmActionPerformed(evt);
            }
        });

        jButton3.setText("Fechar");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mensagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBaunilha, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaunilha, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdm)
                    .addComponent(jButton3))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaunilhaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBaunilhaActionPerformed
    {//GEN-HEADEREND:event_btnBaunilhaActionPerformed
        if (ms.servirSorveteBaunilha())
        {
            this.mensagem.setText("Retire seu sorvete");
        }
        else
        {
            this.mensagem.setText("Desculpe, chame o técnico");
        }
    }//GEN-LAST:event_btnBaunilhaActionPerformed

    private void btnBaunilhaMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnBaunilhaMouseEntered
    {//GEN-HEADEREND:event_btnBaunilhaMouseEntered
        this.mensagem.setText("");
    }//GEN-LAST:event_btnBaunilhaMouseEntered

    private void btnChocolateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnChocolateActionPerformed
    {//GEN-HEADEREND:event_btnChocolateActionPerformed
        if (ms.servirSorveteChocolate())
        {
            this.mensagem.setText("Retire seu sorvete");
        }
        else
        {
            this.mensagem.setText("Desculpe, chame o técnico");
        }
    }//GEN-LAST:event_btnChocolateActionPerformed

    private void btnChocolateMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnChocolateMouseEntered
    {//GEN-HEADEREND:event_btnChocolateMouseEntered
        this.mensagem.setText("");
    }//GEN-LAST:event_btnChocolateMouseEntered

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        MaquinaSorveteDao dao = new MaquinaSorveteDaoTxt();
        dao.save(ms);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnAdmActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAdmActionPerformed
    {//GEN-HEADEREND:event_btnAdmActionPerformed
//        TelaAdmin t = new TelaAdmin(this,ms);
//        t.setVisible(true);
        
        ModuloAdmin moduloAdmin = new ModuloAdmin(this,ms);
        
        Lancador lan = new Lancador(moduloAdmin);
        lan.start();
    }//GEN-LAST:event_btnAdmActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        MaquinaSorveteDao dao = new MaquinaSorveteDaoTxt();
        dao.save(ms);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdm;
    private javax.swing.JButton btnBaunilha;
    private javax.swing.JButton btnChocolate;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mensagem;
    // End of variables declaration//GEN-END:variables
}
